"""ondelete='CASCADE' for user history

Revision ID: 437bf9357e26
Revises: 73b828f94cd1
Create Date: 2023-10-07 19:16:53.773813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437bf9357e26'
down_revision: Union[str, None] = '73b828f94cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_user_id_fkey', 'history', schema='auth', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'user', ['user_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', schema='auth', type_='foreignkey')
    op.create_foreign_key('history_user_id_fkey', 'history', 'user', ['user_id'], ['id'], source_schema='auth', referent_schema='auth')
    # ### end Alembic commands ###
