"""Default datetime, User relations and password_hash length

Revision ID: 73b828f94cd1
Revises: 1ea90922f8f0
Create Date: 2023-10-01 08:18:21.263590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b828f94cd1'
down_revision: Union[str, None] = '1ea90922f8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_role_role_id_fkey', 'api_role', schema='auth', type_='foreignkey')
    op.drop_constraint('api_role_api_id_fkey', 'api_role', schema='auth', type_='foreignkey')
    op.create_foreign_key(None, 'api_role', 'role', ['role_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'api_role', 'api', ['api_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True,
               schema='auth')
    op.drop_constraint('user_role_user_id_fkey', 'user_role', schema='auth', type_='foreignkey')
    op.drop_constraint('user_role_role_id_fkey', 'user_role', schema='auth', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', schema='auth', type_='foreignkey')
    op.drop_constraint(None, 'user_role', schema='auth', type_='foreignkey')
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'role', ['role_id'], ['id'], source_schema='auth', referent_schema='auth')
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'user', ['user_id'], ['id'], source_schema='auth', referent_schema='auth')
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True,
               schema='auth')
    op.drop_constraint(None, 'api_role', schema='auth', type_='foreignkey')
    op.drop_constraint(None, 'api_role', schema='auth', type_='foreignkey')
    op.create_foreign_key('api_role_api_id_fkey', 'api_role', 'api', ['api_id'], ['id'], source_schema='auth', referent_schema='auth')
    op.create_foreign_key('api_role_role_id_fkey', 'api_role', 'role', ['role_id'], ['id'], source_schema='auth', referent_schema='auth')
    # ### end Alembic commands ###
